### ISSUE TITLE
should a keepalive be necessary?

### ISSUE THREAD

**Issue by guruvan** [coreos/flannel#105] opened 2014-12-21 20:24 UTC
In all my work with flannel, it certainly seems that the network between any two hosts will not function until there's a bidirectional flow of traffic between those two hosts.
(i.e:
 from A ping B - fail
from B ping A - fail
from A & B simultaneously reciprocate ping -SUCCESS! :) 

After (some period, not yet measured, but not very long time) of no traffic between A & B the become unreachable until the process is repeated. 

I've written a keepalive unit-pair (dns announcer, and fping+dig script to handle this and keep the network running - but should this be necessary? In most situations, with a loaded network this wouldn't be noticed, but it does present a challenge to bootstrapping the cluster AFAICT. 

The cluster is running in AWS VPC, all etcd machines are in the same AZ, same subnet, -- and this is on the current 522.2 beta.

**Comment by stormltf** [comment] 2015-06-26 13:56
from A ping B - fail
from B ping A - fail
from A & B simultaneously reciprocate ping -SUCCESS! :)

yes, i also have this problem. my docker cluster build in centos 7.0.1406 in openstack kvm.

**Comment by eyakubovich** [comment] 2015-06-26 17:06
@stormltf Can you run tcpdump via [toolbox](https://coreos.com/docs/cluster-management/debugging/install-debugging-tools/) on both src and dest's `flannel0` and also on `eth0` (or whatever the real interface is called). I'm assuming you're using "udp" backend. On `eth0`, the encapsulated packets are sent over udp port 8285 so watch for those.

Also, if you configure it with [vxlan backend](https://github.com/coreos/flannel#backends), does it help?

**Comment by huang503582241** [comment] 2015-06-29 04:05
when i using "udp" backend , i also have that problem.  

when i use vxlan:
./etcdctl mk  /coreos.com/network/config  '{"Network":"192.168.0.0/16","Backend":[{"Type":"vxlan", "VNI": 1}] }'

then i run  flannel in three slave-machines.  all is well.
then i want to start docker  in these three machines.but two of them failed....
[root@vm-56-62 bin]# docker -d --bip=${FLANNEL_SUBNET} --mtu=${FLANNEL_MTU}
INFO[0000] Listening for HTTP on unix (/var/run/docker.sock) 
INFO[0000] [graphdriver] using prior storage driver "devicemapper" 
WARN[0000] Running modprobe bridge nf_nat failed with message: , error: exit status 1 
FATA[0000] Error starting daemon: Error initializing network controller: Error creating default "bridge" network: bridge IPv4 (172.17.42.1) does not match requested configuration 192.168.51.1

**Comment by huang503582241** [comment] 2015-06-29 05:56
when i used "udp" backend ,  i  alse met that problem.

then  i use “vxlan” backend  and  VNI =1 
 i start two machines 
A:  docker0:192.168.51.1      flannel.1: 192.168.51.0
B:  docker0:192.168.99.1      flannel.1: 192.168.99.0

from A PING B   fail
from B PING A fail
from A & B simultaneously reciprocate ping  fail     :(

**Comment by alemagnani** [comment] 2016-10-10 19:12
I am having the same issue described by @guruvan, is there a solution/explanation for it?

**Comment by wb14123** [comment] 2017-02-21 07:24
Hi,

I've had this problem twice and have both found the problem.

The first time is using EC2 and the default safe group didn't open UDP ports. After open them, it works.

The second time is in our own cluster. The first net interface is bind to public IP and have firewall on it. The second interface is used to communication with other hosts in the cluster. Flanneld uses the first interface's IP by default, so it cannot communicate between hosts. After set the IP to use with -iface/--public-ip, it works.

The details of each time is different, but both reasons are hosts cannot communicate on the specify UDP port.

Hope this helps.

**Comment by tomdee** [comment] 2017-04-27 23:21
I think this issue is just caused by firewall ports not being opened. We already mention this in the docs. I'm not sure how else to progress this issue so closing.

**Closed by tomdee** 2017-04-27 23:21 UTC
Labels: kind/question
