### ISSUE TITLE
"Subnet Removed"

### ISSUE THREAD

**Issue by shayts7** [coreos/flannel#283] opened 2015-08-12 13:05 UTC
Hi,

I am running coreos cluster with coreos-vagrant, I'm running 2 coreos machines.
I have docker containers running on both hosts.
After "vagrant up" I checked connectivity between 2 containers running on different host, using "docker exec <local docker container> ping <docker container ip from different host>" - worked like a charm.

After a while the connectivity stopped. Drilling down I found this on logs:
Aug 12 10:41:24 core-02 sdnotify-proxy[940]: I0812 10:41:24.717739 00001 vxlan.go:263] Ignoring not a miss: ee:37:da:54:ca:7d, 10.1.88.2
Aug 12 10:41:26 core-02 sdnotify-proxy[940]: I0812 10:41:26.267041 00001 vxlan.go:284] L3 miss: 10.1.88.2
Aug 12 10:41:26 core-02 sdnotify-proxy[940]: I0812 10:41:26.267157 00001 device.go:242] calling NeighSet: 10.1.88.2, ee:37:da:54:ca:7d
Aug 12 10:41:26 core-02 sdnotify-proxy[940]: I0812 10:41:26.270186 00001 vxlan.go:295] AddL3 succeeded
**Aug 12 10:41:51 core-02 sdnotify-proxy[940]: I0812 10:41:51.779339 00001 vxlan.go:226] Subnet removed: 10.1.88.0/24
Aug 12 10:41:51 core-02 sdnotify-proxy[940]: I0812 10:41:51.779608 00001 device.go:229] calling NeighDel: 172.17.8.101, ee:37:da:54:ca:7d**
Aug 12 10:41:52 core-02 sdnotify-proxy[940]: I0812 10:41:52.280917 00001 vxlan.go:268] L2 miss: ee:37:da:54:ca:7d
Aug 12 10:41:52 core-02 sdnotify-proxy[940]: I0812 10:41:52.281966 00001 vxlan.go:272] Route for ee:37:da:54:ca:7d not found
Aug 12 10:41:52 core-02 sdnotify-proxy[940]: I0812 10:41:52.728781 00001 vxlan.go:268] L2 miss: ee:37:da:54:ca:7d
Aug 12 10:41:52 core-02 sdnotify-proxy[940]: I0812 10:41:52.728892 00001 vxlan.go:272] Route for ee:37:da:54:ca:7d not found
Aug 12 10:41:53 core-02 sdnotify-proxy[940]: I0812 10:41:53.281002 00001 vxlan.go:268] L2 miss: ee:37:da:54:ca:7d

(Highlighted the suspected log prints)
I also checked etcd network/subnets and found out that the entries were removed.

I'm using flannel 0.4.0 from Quay.io
and working with etcd2.

**Comment by eyakubovich** [comment] 2015-08-12 18:53
@shayts7 How long is a while? The only thing that removes subnets is the TTL (lease on the subnet) but that's 24 hours. Did you loose connectivity sooner than that? It shouldn't loose the lease in general since it renews it after 23 hours but at least it's one thing I could see that would cause this.

**Comment by shayts7** [comment] 2015-08-12 21:10
Thanks for the quick response. 
Indeed it was ~24 hours after I provisioned the machines, the renew probably did not work as expected.
Do you have more info about the TTL mechanism (why do we need it, etc..?), Is there a way where I can check that the renewal worked?

**Comment by eyakubovich** [comment] 2015-08-12 21:28
The TTL is needed to remove unused leases. flannel doesn't remove its lease when it is shutdown and we rely on the the TTL to clean obsolete entries up. This is very similar to the original DHCP which didn't have DHCP Release message.

When renewed, you should see `Lease renewed, new expiration: XYZ` in the logs. It should be 23 hours after startup. I would certainly encourage you to move to the latest flannel version (0.5.2) first though.

**Comment by shayts7** [comment] 2015-08-12 21:37
Thanks for the info.

**Comment by MohdAhmad** [comment] 2015-10-08 19:20
@shayts7 did you face any issues with lease renewal after moving to a newer version of flannel?

**Comment by shayts7** [comment] 2015-10-11 09:26
Did not reproduced the use case, so I cannot tell...
If I'll see it again, I'll let you know...

**Comment by steveeJ** [comment] 2016-06-15 00:13
@shayts7 have you been able to reproduce this ever since?

**Comment by shayts7** [comment] 2016-06-15 06:46
@steveeJ  - I did not check that since than...

**Comment by ddysher** [comment] 2016-08-09 04:22
I've see this issue in ubuntu 14.04, kubernetes 1.3.3 and flannel 0.5.5

```
0806 07:48:02.038625 09149 main.go:275] Installing signal handlers
blabla
I0807 08:37:32.625364 09950 vxlan.go:248] Subnet removed: 192.168.68.0/24
```

I was running it with vagrant on local machine; and it stopped working after computer sleep. Based on the log time, it seems TTL is the cause ?

**Comment by sekannia** [comment] 2016-08-25 17:01
Is there a way to increase the TTL or is it 24 hrs

**Comment by tomdee** [comment] 2017-04-27 22:58
@sekannia Currently the TTL is fixed to 24 hours.

I'm going to close this issue - if anyone thinks there's still an issue here then please try to repro on the latest release.

**Closed by tomdee** 2017-04-27 22:58 UTC
Labels: reviewed/needs more information
