### ISSUE TITLE
Flannel issues after restarting Kubernetes Federation

### ISSUE THREAD

**Issue by srinat999** [coreos/flannel#723] opened 2017-05-17 08:22 UTC
I've managed a cross platform Federation up and running. Recently, I changed the default interface of my PC where my federation is running. I went from wired to WiFi. I also had to restart the system in the process. Unfortunately, after this the Federation API server and some other pods are not coming up.

I suspect that the issue with the Flannel container, now that it is not getting attached to the Ethernet interface

## Expected Behavior
All containers should start up and be in running state

## Current Behavior
```
sreenath@ubuntustefan:~/Downloads$ kubectl get pods --all-namespaces
NAMESPACE           NAME                                             READY     STATUS      RESTARTS   AGE
federation-system   asrdemofed-apiserver-658370290-7z4b1             0/2       Completed   2          14d
federation-system   asrdemofed-controller-manager-2848729231-585lr   0/1       Completed   3          14d
kube-system         etcd-ubuntustefan                                1/1       Running     9          18d
kube-system         kube-apiserver-ubuntustefan                      1/1       Running     7          18d
kube-system         kube-controller-manager-ubuntustefan             1/1       Running     6          18d
kube-system         kube-dns-3913472980-3933f                        0/3       Completed   3          18d
kube-system         kube-flannel-ds-s1vkw                            2/2       Running     15         18d
kube-system         kube-proxy-32b1p                                 1/1       Running     5          18d
kube-system         kube-scheduler-ubuntustefan                      1/1       Running     6          18d
kube-system         tiller-deploy-1826578555-vpm54                   0/1       Completed   2          14d
my-namespace        coredns-coredns-2712067778-jbs6g                 0/1       Completed   1          14d
my-namespace        etcd-operator-etcd-opera-574486854-04nlg         0/1       Completed   2          14d
```
## Steps to Reproduce (for bugs)
1. Have a K8S Federation
2. Change the network interface from Ethernet to WiFi
3. Restart the server where the Federation API is running
4. Some of the pods are not starting up

## Context
I'm not able to get my K8S Federation up

## Your Environment
* Flannel version: 0.7.1
* Etcd version: 3.0.17
* Kubernetes version (if used): 1.6.2
* Operating System and version: Ubuntu 16.04

## More Details
```
sreenath@ubuntustefan:~/Downloads$ kubectl describe pod kube-dns-3913472980-3933f --namespace=kube-system
...
  40m       40m     3   kubelet, ubuntustefan           Warning     FailedMount MountVolume.SetUp failed for volume "kubernetes.io/configmap/fc7aa1c0-2c10-11e7-84ef-901b0e3c0827-kube-dns-config" (spec.Name: "kube-dns-config") pod "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827" (UID: "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827") with: Get https://192.168.2.121:6443/api/v1/namespaces/kube-system/configmaps/kube-dns: dial tcp 192.168.2.121:6443: getsockopt: connection refused
  6h        32m     1722    kubelet, ubuntustefan           Normal      SandboxChanged  Pod sandbox changed, it will be killed and re-created.
  6h        32m     1722    kubelet, ubuntustefan           Warning     FailedSync  Error syncing pod, skipping: failed to "KillPodSandbox" for "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-3913472980-3933f_kube-system\" network: open /var/lib/cni/flannel/6b28150e2f8bae1f2c6fd9fbaccd7946d89b335e9243c270cb5ff91e6e50cd0d: no such file or directory"
  19m   19m 1   kubelet, ubuntustefan       Warning FailedSync  Error syncing pod, skipping: failed to "KillPodSandbox" for "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-3913472980-3933f_kube-system\" network: open /var/lib/cni/flannel/9dcd0aeaaf4c17625d4ccf9f407089654d948c82a42c9f55728401be870fc149: no such file or directory"
  18m   18m 6   kubelet, ubuntustefan       Warning FailedMount MountVolume.SetUp failed for volume "kubernetes.io/configmap/fc7aa1c0-2c10-11e7-84ef-901b0e3c0827-kube-dns-config" (spec.Name: "kube-dns-config") pod "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827" (UID: "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827") with: Get https://192.168.2.121:6443/api/v1/namespaces/kube-system/configmaps/kube-dns: dial tcp 192.168.2.121:6443: getsockopt: connection refused
  30m   13s 142 kubelet, ubuntustefan       Normal  SandboxChanged  Pod sandbox changed, it will be killed and re-created.
  30m   13s 141 kubelet, ubuntustefan       Warning FailedSync  Error syncing pod, skipping: failed to "KillPodSandbox" for "fc7aa1c0-2c10-11e7-84ef-901b0e3c0827" with KillPodSandboxError: "rpc error: code = 2 desc = NetworkPlugin cni failed to teardown pod \"kube-dns-3913472980-3933f_kube-system\" network: open /var/lib/cni/flannel/6b28150e2f8bae1f2c6fd9fbaccd7946d89b335e9243c270cb5ff91e6e50cd0d: no such file or directory"
sreenath@ubuntustefan:~/Downloads$ sudo docker logs 59a2604179f8 (flannel container)
I0516 15:18:43.720866       1 kube.go:111] Waiting 10m0s for node controller to sync
I0516 15:18:43.720950       1 kube.go:315] starting kube subnet manager
I0516 15:18:44.721165       1 kube.go:118] Node controller sync successful
I0516 15:18:44.721195       1 main.go:132] Installing signal handlers
I0516 15:18:44.721299       1 manager.go:136] Determining IP address of default interface
I0516 15:18:44.721614       1 manager.go:149] Using interface with name wlx086a0a70c0ed and address 10.192.151.66
I0516 15:18:44.721638       1 manager.go:166] Defaulting external address to interface address (10.192.151.66)
I0516 15:18:44.723266       1 ipmasq.go:47] Adding iptables rule: -s 10.244.0.0/16 -d 10.244.0.0/16 -j RETURN
I0516 15:18:44.724189       1 ipmasq.go:47] Adding iptables rule: -s 10.244.0.0/16 ! -d 224.0.0.0/4 -j MASQUERADE
I0516 15:18:44.725233       1 ipmasq.go:47] Adding iptables rule: ! -s 10.244.0.0/16 -d 10.244.0.0/16 -j MASQUERADE
I0516 15:18:44.726262       1 manager.go:250] Lease acquired: 10.244.0.0/24
I0516 15:18:44.726415       1 network.go:58] Watching for L3 misses
I0516 15:18:44.726447       1 network.go:66] Watching for new subnet leases
1 Comment Collapse
```

**Comment by tomdee** [comment] 2017-05-17 17:40
@srinat999 I can't really tell if this is a bug or not. I've not done any testing with federations and so it's not currently supported with flannel. 

But - flannel is not involved in the startup of pods, so from your description above I can't see how flannel is the issue. 

I can't spin up a federation and start switching from wired to wifi to try to repro this complex issue, so I'm closing this. 

If you can come up with a simpler repro and a better reason why this is caused by flannel then I can reopen the issue.

**Closed by tomdee** 2017-05-17 17:40 UTC
