### ISSUE TITLE
Why flannel hides (SNAT/MASQ?) original src IP in packets?

### ISSUE THREAD

**Issue by piontec** [coreos/flannel#835] opened 2017-10-10 10:32 UTC
I'm trying to use flannel to provide networking across docker hosts running legacy application. For these applications, it is essential to learn original source IP of the client initiating a connection. Unfortunately, it seems that flannel "hides" source IP. Is it by design? Is it possible to bypass this limitation?

## My setup and current behaviour
I got a node "wn3", where `docker0: 10.5.50.1/24`  and `flannel.1: 10.5.50.0/32` (flannel subnet is 10.5.0.0/16). On this host, there's a container running with `10.5.50.2`. Now, on another node `wn2`, I got: `docker0: 10.5.40.1/24` and `flannel.1: 10.5.40.0/32`. On `wn2` I'm starting a new container, it gets `10.5.40.3/24`.  I ping `10.5.50.2` from this container. Now, on `wn3` I'm capturing traffic on `docker0` and I see:
 ```   
15 53.676966912    10.5.40.0 → 10.5.50.2    ICMP 98 Echo (ping) request  id=0x0600, seq=0/0, ttl=62
16 53.676990202    10.5.50.2 → 10.5.40.0    ICMP 98 Echo (ping) reply    id=0x0600, seq=0/0, ttl=64 (request in 15)
```
So traffic appears coming from `10.5.40.0`, not from `10.5.40.3` as I would expect. Why flannel does that? routing for the original IP is set correctly, so why to MASQ/SNAT it?
 ```
root@wn-3:~# ip r g 10.5.40.3
10.5.40.3 dev flannel.1  src 10.5.50.0 
    cache
```

## Expected Behavior
I would expect the original IP `10.5.40.3` to be present as src IP instead of the IP of the flannel tunnel on the host - `10.5.40.0`.

## Your Environment
* Flannel version: 0.8.0
* Backend used (e.g. vxlan or udp): VXLAN
* Etcd version: 3.2.8
* Kubernetes version (if used): none
* Operating System and version: ubuntu 16.04

**Comment by mgleung** [comment] 2017-10-10 16:48
What happens if you do a packet capture on the interface for the container on `wn3` in the example above?   I believe that at the host, if you capture packets, you will see the the tunnel IP, but if you were to  capture packets at the destination container interface on `wn3` you should be seeing the source IP for the container on `wn2`. Let me know if that works for you.

**Comment by mgleung** [comment] 2017-10-10 17:44
That definitely seems to be unexpected behavior.  Can you make sure that your docker daemon and your flannel config have the `ip-masq` option set to `false` and try restarting docker to see if that works?  I noticed that the `ip-masq` option for the docker daemon defaults to `true` so that might possibly be the issue.

**Comment by piontec** [comment] 2017-10-11 12:16
@mgleung Thanks for the answer, but if that's unexpected, it means 2 things to me:
1. flannel should be a perfect solution to my problems
2. I'm totally lost and got no idea why I can't make it work :(

Can I ask for help here?

Let me give you some more data now:
1. nodes config
  * wn2: docker0: 10.5.89.1/24, flannel.1: 10.5.89.0/32
  * wn3: docker0: 10.5.47.1/24, flannel.1: 10.5.47.0/32
  * etcd: v3.2.8, the simplest setup that was good enough for testing, 1 node, no security
  * flanneld: I upgraded to 0.9.0 today, but no change :(
  * docker running with
```
    "userland-proxy": false,
    "iptables": false,
    "ip-forward": true,
    "ip-masq": false
```
  * I checked iptables
    * for table `filter` - no rules, all policies to `ACCEPT`
    * for table `nat` some stuff set by flannel to masq traffic going out; just to be sure it's not messing up anything, I `F`lushed the whole POSTROUTING chain; end result: all chains empty and set to `ACCEPT`
  * flanneld start command `ExecStart=/usr/local/bin/flanneld -v 4 -iface eth0 -etcd-endpoints 'http://10.237.33.235:2379' --healthz-port=8090` on both nodes

2. Test results
  * on `wn3` I'm starting tcpdump in a container, it gets `10.5.47.3`
```
# docker run -it --name tcpd --rm  corfr/tcpdump -n -i eth0
```
  * on `wn2`, I'm pinging tcpdump container on `wn3` from aother container
```
# docker run -it --rm alpine ip a && ping 10.5.47.3
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
196: eth0@if197: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 8951 qdisc noqueue state UP 
    link/ether 02:42:0a:05:59:02 brd ff:ff:ff:ff:ff:ff
    inet 10.5.89.2/24 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:aff:fe05:5902/64 scope link tentative 
       valid_lft forever preferred_lft forever
PING 10.5.47.3 (10.5.47.3) 56(84) bytes of data.
64 bytes from 10.5.47.3: icmp_seq=7 ttl=63 time=0.589 ms
64 bytes from 10.5.47.3: icmp_seq=8 ttl=63 time=0.610 ms
```

and the tcpdump is
```
# docker run -it --name tcpd --rm  corfr/tcpdump -n -i eth0
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on eth0, link-type EN10MB (Ethernet), capture size 262144 bytes
12:10:14.131073 ARP, Request who-has 10.5.47.3 tell 10.5.47.1, length 28
12:10:14.131090 ARP, Reply 10.5.47.3 is-at 02:42:0a:05:2f:03, length 28
12:10:14.168889 IP 10.5.89.0 > 10.5.47.3: ICMP echo request, id 25685, seq 7, length 64
12:10:14.168913 IP 10.5.47.3 > 10.5.89.0: ICMP echo reply, id 25685, seq 7, length 64
...
```

Conclusions: definitely not working, src IP is masqueraded, but no MASQ done in iptables. What am I doing wrong?

**Comment by piontec** [comment] 2017-10-11 12:23
Afterall, it doesn't feel unexpected, please check dumps showed on this page - they exactly confirm my findings:
http://docker-k8s-lab.readthedocs.io/en/latest/docker/docker-flannel.html

**Comment by mgleung** [comment] 2017-10-11 19:37
Can you post the output of `iptables-save`? I also vaguely recall a similar issue to this for flannel on kubernetes that was resolved which I thought had something to do with the iptables rules. Can you also try enabling the flannel `ip-masq` option? I noticed that its enabled as a part of a default kubernetes install using the example manifest files, and I was wondering if that will make a difference.

**Comment by piontec** [comment] 2017-10-23 12:25
I can't really recreate the testing environment now, so also no `iptables-save`. But please note I did check iptables in the previous one:
> I checked iptables
> for table filter - no rules, all policies to ACCEPT
> for table nat some stuff set by flannel to masq traffic going out; just to be sure it's not messing up  anything, I Flushed the whole POSTROUTING chain; end result: all chains empty and set to ACCEPT

So I'm pretty sure it's not iptables - I flushed everything manually. Can you give me a setup/config that is expected to work? Maybe I can recreate it and then verify again?

**Comment by tomdee** [comment] 2017-11-03 22:49
Hi @piontec your debugging seems pretty thorough but it still comes as a surprise. I've tried to reproduce this on Coreos container linux but I was unable to. I used both the UDP and vxlan backends.

I'm not really sure what to suggest. Maybe you can run tcpdump at a few different places to try to isolate where the mangling is happening (e.g. the bridge, the vxlan device and the physical ethernet device).

**Comment by tomdee** [comment] 2017-11-24 16:04
@piontec I'm closing this as I can't repro. I can reopen if you can provide more info.

**Closed by tomdee** 2017-11-24 16:04 UTC
Labels: component/masq, reviewed/needs more information

**Comment by harryge00** [comment] 2018-02-28 13:07
I have encountered similar issue:

I have two kube-nodes:
* node1: 
```
6: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:61:51:7d:e5 brd ff:ff:ff:ff:ff:ff
    inet 172.16.43.1/25 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:61ff:fe51:7de5/64 scope link 
       valid_lft forever preferred_lft forever
7: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 0e:47:17:48:a4:27 brd ff:ff:ff:ff:ff:ff
    inet 172.16.43.0/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::c47:17ff:fe48:a427/64 scope link 
       valid_lft forever preferred_lft forever
```
* node2:
```
6: flannel.1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UNKNOWN group default 
    link/ether 82:94:82:80:b8:ad brd ff:ff:ff:ff:ff:ff
    inet 172.16.5.128/32 scope global flannel.1
       valid_lft forever preferred_lft forever
    inet6 fe80::8094:82ff:fe80:b8ad/64 scope link 
       valid_lft forever preferred_lft forever
8: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:42:a4:90:57:1a brd ff:ff:ff:ff:ff:ff
    inet 172.16.5.129/25 scope global docker0
       valid_lft forever preferred_lft forever
    inet6 fe80::42:a4ff:fe90:571a/64 scope link 
       valid_lft forever preferred_lft forever
```

And I have two pods running on each nodes. 
```
NAME             READY     STATUS    RESTARTS   AGE       IP             NODE
nettools-9nv2p   1/1       Running   0          14m       172.16.43.3        node1
nettools-9x4qx   1/1       Running   0          14m       172.16.5.135      node2
```
When I run `curl` or `ping` from `nettools-9nv2p`, the source ip of packet received by `nettools-9x4qx`  is always `172.16.43.0` instead of `172.16.43.3`

**Comment by harryge00** [comment] 2018-02-28 13:11
node1 iptables-save
```
# Generated by iptables-save v1.4.21 on Wed Feb 28 21:07:48 2018
*nat
:PREROUTING ACCEPT [3:2018]
:INPUT ACCEPT [3:2018]
:OUTPUT ACCEPT [0:0]
:POSTROUTING ACCEPT [0:0]
:DOCKER - [0:0]
:KUBE-MARK-DROP - [0:0]
:KUBE-MARK-MASQ - [0:0]
:KUBE-NODEPORTS - [0:0]
:KUBE-POSTROUTING - [0:0]
:KUBE-SEP-FCHYNVOFOFGIUMBY - [0:0]
:KUBE-SEP-HHWB6LZJMIGR5XXK - [0:0]
:KUBE-SEP-MUBB2Z3OVVL6V33J - [0:0]
:KUBE-SEP-NGMB3JPUZFP6PS74 - [0:0]
:KUBE-SEP-NZZG5KOED226L2BS - [0:0]
:KUBE-SEP-O7LWMRG4EUHSMHCJ - [0:0]
:KUBE-SEP-U7Z6EIYCKKY42PB3 - [0:0]
:KUBE-SEP-ZIPXOZUFXEMI6YRM - [0:0]
:KUBE-SERVICES - [0:0]
:KUBE-SVC-5Y3ZLF3EYCHWWCPP - [0:0]
:KUBE-SVC-65L4FYUNF7YDTIJK - [0:0]
:KUBE-SVC-6NPOPAOKYQI2CXFZ - [0:0]
:KUBE-SVC-744NWWTJENSRJDPJ - [0:0]
:KUBE-SVC-ATBKJ73LCHUJRUNC - [0:0]
:KUBE-SVC-BJM46V3U5RZHCFRZ - [0:0]
:KUBE-SVC-CIHUDM46N7ZCFQST - [0:0]
:KUBE-SVC-CN7V3TONCZIRUOUE - [0:0]
:KUBE-SVC-FBUMKHPBL2G76GJH - [0:0]
:KUBE-SVC-JRMGSERZMV7B5FJO - [0:0]
:KUBE-SVC-JZNZHRYDTXOSXXAS - [0:0]
:KUBE-SVC-K7J76NXP7AUZVFGS - [0:0]
:KUBE-SVC-KW5YRSH6ET4ZIMNW - [0:0]
:KUBE-SVC-NPX46M4PTMTKRN6Y - [0:0]
:KUBE-SVC-OREPFSATFRFITUEU - [0:0]
:KUBE-SVC-S65OFF6UWIWRJSLS - [0:0]
:KUBE-SVC-TGESM7SD6G7BCDQS - [0:0]
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.16.43.0/25 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
-A KUBE-SEP-FCHYNVOFOFGIUMBY -s 172.16.5.149/32 -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-3" -j KUBE-MARK-MASQ
-A KUBE-SEP-FCHYNVOFOFGIUMBY -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-3" -m tcp -j DNAT --to-destination 172.16.5.149:38052
-A KUBE-SEP-HHWB6LZJMIGR5XXK -s 172.16.5.149/32 -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-2" -j KUBE-MARK-MASQ
-A KUBE-SEP-HHWB6LZJMIGR5XXK -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-2" -m tcp -j DNAT --to-destination 172.16.5.149:38209
-A KUBE-SEP-MUBB2Z3OVVL6V33J -s 172.16.5.151/32 -m comment --comment "wubo-49/intelligencenode:intelligencenode-0" -j KUBE-MARK-MASQ
-A KUBE-SEP-MUBB2Z3OVVL6V33J -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-0" -m tcp -j DNAT --to-destination 172.16.5.151:5000
-A KUBE-SEP-NGMB3JPUZFP6PS74 -s 172.16.5.151/32 -m comment --comment "wubo-49/intelligencenode:intelligencenode-2" -j KUBE-MARK-MASQ
-A KUBE-SEP-NGMB3JPUZFP6PS74 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-2" -m tcp -j DNAT --to-destination 172.16.5.151:38052
-A KUBE-SEP-NZZG5KOED226L2BS -s 172.16.5.149/32 -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-1" -j KUBE-MARK-MASQ
-A KUBE-SEP-NZZG5KOED226L2BS -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-1" -m tcp -j DNAT --to-destination 172.16.5.149:38208
-A KUBE-SEP-O7LWMRG4EUHSMHCJ -s 172.16.5.151/32 -m comment --comment "wubo-49/intelligencenode:intelligencenode-1" -j KUBE-MARK-MASQ
-A KUBE-SEP-O7LWMRG4EUHSMHCJ -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-1" -m tcp -j DNAT --to-destination 172.16.5.151:38212
-A KUBE-SEP-U7Z6EIYCKKY42PB3 -s 172.16.5.149/32 -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-0" -j KUBE-MARK-MASQ
-A KUBE-SEP-U7Z6EIYCKKY42PB3 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-0" -m tcp -j DNAT --to-destination 172.16.5.149:5000
-A KUBE-SEP-ZIPXOZUFXEMI6YRM -s 10.35.48.169/32 -m comment --comment "default/kubernetes:https" -j KUBE-MARK-MASQ
-A KUBE-SEP-ZIPXOZUFXEMI6YRM -p tcp -m comment --comment "default/kubernetes:https" -m recent --set --name KUBE-SEP-ZIPXOZUFXEMI6YRM --mask 255.255.255.255 --rsource -m tcp -j DNAT --to-destination 10.35.48.169:6443
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-3 cluster IP" -m tcp --dport 38209 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-3 cluster IP" -m tcp --dport 38209 -j KUBE-SVC-JZNZHRYDTXOSXXAS
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-0 cluster IP" -m tcp --dport 5000 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-0 cluster IP" -m tcp --dport 5000 -j KUBE-SVC-OREPFSATFRFITUEU
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-2 cluster IP" -m tcp --dport 38052 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-2 cluster IP" -m tcp --dport 38052 -j KUBE-SVC-65L4FYUNF7YDTIJK
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.0.1/32 -p tcp -m comment --comment "default/kubernetes:https cluster IP" -m tcp --dport 443 -j KUBE-SVC-NPX46M4PTMTKRN6Y
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-1 cluster IP" -m tcp --dport 38208 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-1 cluster IP" -m tcp --dport 38208 -j KUBE-SVC-JRMGSERZMV7B5FJO
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.150.157/32 -p tcp -m comment --comment "kube-system/tiller-deploy:tiller cluster IP" -m tcp --dport 44134 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.150.157/32 -p tcp -m comment --comment "kube-system/tiller-deploy:tiller cluster IP" -m tcp --dport 44134 -j KUBE-SVC-K7J76NXP7AUZVFGS
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.194.111/32 -p tcp -m comment --comment "zhangyuandao-1/myservice73:myservice73-0 cluster IP" -m tcp --dport 5689 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.194.111/32 -p tcp -m comment --comment "zhangyuandao-1/myservice73:myservice73-0 cluster IP" -m tcp --dport 5689 -j KUBE-SVC-6NPOPAOKYQI2CXFZ
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-3 cluster IP" -m tcp --dport 38052 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-3 cluster IP" -m tcp --dport 38052 -j KUBE-SVC-5Y3ZLF3EYCHWWCPP
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-0 cluster IP" -m tcp --dport 5000 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-0 cluster IP" -m tcp --dport 5000 -j KUBE-SVC-744NWWTJENSRJDPJ
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-1 cluster IP" -m tcp --dport 38052 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-1 cluster IP" -m tcp --dport 38052 -j KUBE-SVC-CN7V3TONCZIRUOUE
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-2 cluster IP" -m tcp --dport 38208 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-2 cluster IP" -m tcp --dport 38208 -j KUBE-SVC-FBUMKHPBL2G76GJH
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.103.130/32 -p tcp -m comment --comment "wubo-49/intelligence-master-zyd: cluster IP" -m tcp --dport 38209 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.103.130/32 -p tcp -m comment --comment "wubo-49/intelligence-master-zyd: cluster IP" -m tcp --dport 38209 -j KUBE-SVC-TGESM7SD6G7BCDQS
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-1 cluster IP" -m tcp --dport 38212 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.200.103/32 -p tcp -m comment --comment "wubo-49/intelligencenode:intelligencenode-1 cluster IP" -m tcp --dport 38212 -j KUBE-SVC-KW5YRSH6ET4ZIMNW
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-0 cluster IP" -m tcp --dport 5000 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-0 cluster IP" -m tcp --dport 5000 -j KUBE-SVC-S65OFF6UWIWRJSLS
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-2 cluster IP" -m tcp --dport 38209 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.35.177/32 -p tcp -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-2 cluster IP" -m tcp --dport 38209 -j KUBE-SVC-CIHUDM46N7ZCFQST
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.95.82/32 -p tcp -m comment --comment "zhangyuandao-1/testservice73:testservice73-0 cluster IP" -m tcp --dport 7894 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.95.82/32 -p tcp -m comment --comment "zhangyuandao-1/testservice73:testservice73-0 cluster IP" -m tcp --dport 7894 -j KUBE-SVC-ATBKJ73LCHUJRUNC
-A KUBE-SERVICES ! -s 10.252.0.0/16 -d 10.0.186.226/32 -p tcp -m comment --comment "kube-system/heapster: cluster IP" -m tcp --dport 80 -j KUBE-MARK-MASQ
-A KUBE-SERVICES -d 10.0.186.226/32 -p tcp -m comment --comment "kube-system/heapster: cluster IP" -m tcp --dport 80 -j KUBE-SVC-BJM46V3U5RZHCFRZ
-A KUBE-SERVICES -m comment --comment "kubernetes service nodeports; NOTE: this must be the last rule in this chain" -m addrtype --dst-type LOCAL -j KUBE-NODEPORTS
-A KUBE-SVC-5Y3ZLF3EYCHWWCPP -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-3" -j KUBE-SEP-FCHYNVOFOFGIUMBY
-A KUBE-SVC-65L4FYUNF7YDTIJK -m comment --comment "wubo-49/intelligencenode:intelligencenode-2" -j KUBE-SEP-NGMB3JPUZFP6PS74
-A KUBE-SVC-CIHUDM46N7ZCFQST -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-2" -j KUBE-SEP-HHWB6LZJMIGR5XXK
-A KUBE-SVC-JRMGSERZMV7B5FJO -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-1" -j KUBE-SEP-NZZG5KOED226L2BS
-A KUBE-SVC-KW5YRSH6ET4ZIMNW -m comment --comment "wubo-49/intelligencenode:intelligencenode-1" -j KUBE-SEP-O7LWMRG4EUHSMHCJ
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -m recent --rcheck --seconds 10800 --reap --name KUBE-SEP-ZIPXOZUFXEMI6YRM --mask 255.255.255.255 --rsource -j KUBE-SEP-ZIPXOZUFXEMI6YRM
-A KUBE-SVC-NPX46M4PTMTKRN6Y -m comment --comment "default/kubernetes:https" -j KUBE-SEP-ZIPXOZUFXEMI6YRM
-A KUBE-SVC-OREPFSATFRFITUEU -m comment --comment "wubo-49/intelligencenode:intelligencenode-0" -j KUBE-SEP-MUBB2Z3OVVL6V33J
-A KUBE-SVC-S65OFF6UWIWRJSLS -m comment --comment "wubo-49/intelligencemaster:intelligencemaster-0" -j KUBE-SEP-U7Z6EIYCKKY42PB3
COMMIT
# Completed on Wed Feb 28 21:07:48 2018
# Generated by iptables-save v1.4.21 on Wed Feb 28 21:07:48 2018
*filter
:INPUT ACCEPT [14:6332]
:FORWARD ACCEPT [0:0]
:OUTPUT ACCEPT [3:244]
:DOCKER - [0:0]
:DOCKER-ISOLATION - [0:0]
:KUBE-FIREWALL - [0:0]
:KUBE-SERVICES - [0:0]
-A INPUT -j KUBE-FIREWALL
-A FORWARD -j DOCKER-ISOLATION
-A FORWARD -o docker0 -j DOCKER
-A FORWARD -o docker0 -m conntrack --ctstate RELATED,ESTABLISHED -j ACCEPT
-A FORWARD -i docker0 ! -o docker0 -j ACCEPT
-A FORWARD -i docker0 -o docker0 -j ACCEPT
-A FORWARD -s 172.16.0.0/16 -j ACCEPT
-A FORWARD -d 172.16.0.0/16 -j ACCEPT
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT -j KUBE-FIREWALL
-A DOCKER-ISOLATION -j RETURN
-A KUBE-FIREWALL -m comment --comment "kubernetes firewall for dropping marked packets" -m mark --mark 0x8000/0x8000 -j DROP
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-3 has no endpoints" -m tcp --dport 38209 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.150.157/32 -p tcp -m comment --comment "kube-system/tiller-deploy:tiller has no endpoints" -m tcp --dport 44134 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.194.111/32 -p tcp -m comment --comment "zhangyuandao-1/myservice73:myservice73-0 has no endpoints" -m tcp --dport 5689 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-0 has no endpoints" -m tcp --dport 5000 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-1 has no endpoints" -m tcp --dport 38052 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.222.109/32 -p tcp -m comment --comment "wubo-49/intelligence-master-v0628003:intelligence-master-v0628003-2 has no endpoints" -m tcp --dport 38208 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.103.130/32 -p tcp -m comment --comment "wubo-49/intelligence-master-zyd: has no endpoints" -m tcp --dport 38209 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.95.82/32 -p tcp -m comment --comment "zhangyuandao-1/testservice73:testservice73-0 has no endpoints" -m tcp --dport 7894 -j REJECT --reject-with icmp-port-unreachable
-A KUBE-SERVICES -d 10.0.186.226/32 -p tcp -m comment --comment "kube-system/heapster: has no endpoints" -m tcp --dport 80 -j REJECT --reject-with icmp-port-unreachable
COMMIT
# Completed on Wed Feb 28 21:07:48 2018
```

**Comment by harryge00** [comment] 2018-02-28 13:13
node1 ip-tables
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
-A POSTROUTING -s 172.16.43.0/25 ! -o docker0 -j MASQUERADE
-A DOCKER -i docker0 -j RETURN
-A KUBE-MARK-DROP -j MARK --set-xmark 0x8000/0x8000
-A KUBE-MARK-MASQ -j MARK --set-xmark 0x4000/0x4000
-A KUBE-POSTROUTING -m comment --comment "kubernetes service traffic requiring SNAT" -m mark --mark 0x4000/0x4000 -j MASQUERADE
```
node2
```
-A PREROUTING -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A PREROUTING -m addrtype --dst-type LOCAL -j DOCKER
-A OUTPUT -m comment --comment "kubernetes service portals" -j KUBE-SERVICES
-A OUTPUT ! -d 127.0.0.0/8 -m addrtype --dst-type LOCAL -j DOCKER
-A POSTROUTING -s 172.16.5.128/25 ! -o docker0 -j MASQUERADE
-A POSTROUTING -m comment --comment "kubernetes postrouting rules" -j KUBE-POSTROUTING
```

**Comment by harryge00** [comment] 2018-02-28 13:26
I clear old iptables produces by old version flanneld. And the source ip is correct now...

https://github.com/coreos/flannel/issues/864

**Comment by harryge00** [comment] 2018-03-02 07:24
Solved after clearing old iptable rules.

**Comment by apple0407** [comment] 2019-03-19 06:31
> Solved after clearing old iptable rules. And add `--iptables=false --ip-masq=false` to dockerd args

@harryge00 
yes, by this way i can get the real ip. But i get another problem, with `--ip-masq=false` , within container, i can't connect to the internet, or any  other hosts in the host's network.  

But within the container, i can still connect to  containers on other nodes via flannel

i just can't figure out how this happen.
