### ISSUE TITLE
Error registering network: operation not supported

### ISSUE THREAD

**Issue by dig** [coreos/flannel#1028] opened 2018-08-12 18:52 UTC
## Expected Behavior
I have a single cluster master server on kubernetes and I'm going to be using flannel as the pod network addon.

## Current Behavior
Flannel constantly crashLoopBackOff state after fresh install on CentOS 7. The logs show that flannel is outputting Error registering network: operation not supported.

## Possible Solution
- `CONFIG_VXLAN: missing` might be the problem when I use the docker check-config.sh file. Output of the entire check-config.sh can be found here, https://pastebin.com/XR1stjWc.

## Steps to Reproduce (for bugs)
1. Install kubernetes and docker
2. Run kubeadm init --pod-network-cidr=10.244.0.0/16
3. Run kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
4. Run kubectl get pods --all-namespaces [Output](https://felfire.me/KoPefZCmsI.png)

## Context
Unable to use networking in kubernetes.

## Your Environment

* Flannel version: v0.10.0
* Backend used (e.g. vxlan or udp): VXLAN (
* Etcd version: N/A
* Kubernetes version (if used): v1.11.2
* Operating System and version: CentOS 7 (Linux SMP Mon Aug 6 15:28:47 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux)
* Link to your project (optional): N/A

**Comment by LinuxEA-Mark** [comment] 2018-08-19 10:36
After I was running for 34 minutes, there was a problem with his status.

```
 kubectl get pods --all-namespaces 
NAMESPACE     NAME                                           READY     STATUS              RESTARTS   AGE
kube-system   coredns-78fcdf6894-gxzvk                       0/1       ContainerCreating   0          34m
kube-system   coredns-78fcdf6894-qt2zq                       0/1       ContainerCreating   0          34m
```
But after I opened docker ps -a, I found that this container has been Exited (0) 26 minutes ago
```
F4410baaf5c3 f0fad859c909 "cp -f /etc/kube-f..." 26 minutes ago Exited (0) 26 minutes ago k8s_install-cni_kube-flannel-ds-amd64-7xphb_kube-system_b9181d5d-a396-11e8-aaf5-88882f0da0b5_0
```
And, what is he constantly trying?
```
fc01139716cf        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                                   k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1520
0be80323c554        k8s.gcr.io/pause:3.1   "/pause"                 Less than a second ago   Up Less than a second                                   k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1515
8035bc0ff9eb        k8s.gcr.io/pause:3.1   "/pause"                 1 second ago             Exited (0) Less than a second ago                       k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1514
1ded83fd1bcc        k8s.gcr.io/pause:3.1   "/pause"                 1 second ago             Exited (0) 1 second ago                                 k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1519
be4936c45c05        k8s.gcr.io/pause:3.1   "/pause"                 2 seconds ago            Exited (0) 1 second ago                                 k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1513
c6b37e314c0b        k8s.gcr.io/pause:3.1   "/pause"                 3 seconds ago            Exited (0) 2 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1518
d5ebfcd313a8        k8s.gcr.io/pause:3.1   "/pause"                 4 seconds ago            Exited (0) 3 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1512
206a64561310        k8s.gcr.io/pause:3.1   "/pause"                 5 seconds ago            Exited (0) 4 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1511
bdeda43c4d6d        k8s.gcr.io/pause:3.1   "/pause"                 5 seconds ago            Exited (0) 4 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1517
0dcecd20317f        k8s.gcr.io/pause:3.1   "/pause"                 6 seconds ago            Exited (0) 5 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1510
88eafefb9665        k8s.gcr.io/pause:3.1   "/pause"                 6 seconds ago            Exited (0) 5 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1516
56077c076d57        k8s.gcr.io/pause:3.1   "/pause"                 7 seconds ago            Exited (0) 6 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1509
5e403d699ea6        k8s.gcr.io/pause:3.1   "/pause"                 7 seconds ago            Exited (0) 6 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1515
fb8cad37eb9c        k8s.gcr.io/pause:3.1   "/pause"                 8 seconds ago            Exited (0) 7 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1508
633cdd7266a7        k8s.gcr.io/pause:3.1   "/pause"                 8 seconds ago            Exited (0) 7 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1514
f2a20ec7588c        k8s.gcr.io/pause:3.1   "/pause"                 9 seconds ago            Exited (0) 8 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1513
f185cae55cfb        k8s.gcr.io/pause:3.1   "/pause"                 9 seconds ago            Exited (0) 8 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1507
a088f481902a        k8s.gcr.io/pause:3.1   "/pause"                 10 seconds ago           Exited (0) 9 seconds ago                                k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1512
682c09da3e80        k8s.gcr.io/pause:3.1   "/pause"                 10 seconds ago           Exited (0) 9 seconds ago                                k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1506
6f7420ec4d56        k8s.gcr.io/pause:3.1   "/pause"                 11 seconds ago           Exited (0) 10 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1505
fd27fb711987        k8s.gcr.io/pause:3.1   "/pause"                 11 seconds ago           Exited (0) 10 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1511
0512624609b2        k8s.gcr.io/pause:3.1   "/pause"                 12 seconds ago           Exited (0) 11 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1504
474e5ecad1d2        k8s.gcr.io/pause:3.1   "/pause"                 12 seconds ago           Exited (0) 11 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1510
7a9a981b9351        k8s.gcr.io/pause:3.1   "/pause"                 13 seconds ago           Exited (0) 12 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1503
caff8bc0d65c        k8s.gcr.io/pause:3.1   "/pause"                 13 seconds ago           Exited (0) 13 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1509
a2201e43c624        k8s.gcr.io/pause:3.1   "/pause"                 14 seconds ago           Exited (0) 13 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1502
34219b8788cb        k8s.gcr.io/pause:3.1   "/pause"                 14 seconds ago           Exited (0) 14 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1508
dac2e43f193d        k8s.gcr.io/pause:3.1   "/pause"                 15 seconds ago           Exited (0) 14 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1507
4a3eb2e8d96b        k8s.gcr.io/pause:3.1   "/pause"                 16 seconds ago           Exited (0) 15 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1501
a2df34006889        k8s.gcr.io/pause:3.1   "/pause"                 17 seconds ago           Exited (0) 16 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1506
48dd35cfa0b8        k8s.gcr.io/pause:3.1   "/pause"                 17 seconds ago           Exited (0) 16 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1500
db0e2f608438        k8s.gcr.io/pause:3.1   "/pause"                 18 seconds ago           Exited (0) 17 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1505
e7d5b5b357ee        k8s.gcr.io/pause:3.1   "/pause"                 18 seconds ago           Exited (0) 17 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1499
ef98353f9e2c        k8s.gcr.io/pause:3.1   "/pause"                 19 seconds ago           Exited (0) 18 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1504
a68ee413a143        k8s.gcr.io/pause:3.1   "/pause"                 19 seconds ago           Exited (0) 18 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1498
d8ac70534d20        k8s.gcr.io/pause:3.1   "/pause"                 20 seconds ago           Exited (0) 19 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1497
a2175e909e69        k8s.gcr.io/pause:3.1   "/pause"                 20 seconds ago           Exited (0) 19 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1503
3e11faa198f6        k8s.gcr.io/pause:3.1   "/pause"                 21 seconds ago           Exited (0) 20 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1502
aff6aafe64c3        k8s.gcr.io/pause:3.1   "/pause"                 22 seconds ago           Exited (0) 20 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1496
5355ed246d45        k8s.gcr.io/pause:3.1   "/pause"                 23 seconds ago           Exited (0) 22 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1495
a89ea7a1268b        k8s.gcr.io/pause:3.1   "/pause"                 23 seconds ago           Exited (0) 21 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1501
4820f8760791        k8s.gcr.io/pause:3.1   "/pause"                 24 seconds ago           Exited (0) 23 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1494
e75ebfbfc557        k8s.gcr.io/pause:3.1   "/pause"                 24 seconds ago           Exited (0) 23 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1500
ac9753b04b28        k8s.gcr.io/pause:3.1   "/pause"                 25 seconds ago           Exited (0) 24 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1493
f22928ff2541        k8s.gcr.io/pause:3.1   "/pause"                 26 seconds ago           Exited (0) 25 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1492
46fa07b02398        k8s.gcr.io/pause:3.1   "/pause"                 26 seconds ago           Exited (0) 25 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1499
218ac00a8f0d        k8s.gcr.io/pause:3.1   "/pause"                 27 seconds ago           Exited (0) 26 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1491
41c16f2d4574        k8s.gcr.io/pause:3.1   "/pause"                 27 seconds ago           Exited (0) 26 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1498
609f046d265d        k8s.gcr.io/pause:3.1   "/pause"                 28 seconds ago           Exited (0) 27 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1490
86723f547525        k8s.gcr.io/pause:3.1   "/pause"                 29 seconds ago           Exited (0) 28 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1497
e142d90a5400        k8s.gcr.io/pause:3.1   "/pause"                 29 seconds ago           Exited (0) 28 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1489
a608b882c687        k8s.gcr.io/pause:3.1   "/pause"                 30 seconds ago           Exited (0) 29 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1496
d8babda49694        k8s.gcr.io/pause:3.1   "/pause"                 31 seconds ago           Exited (0) 30 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1488
989b36513067        k8s.gcr.io/pause:3.1   "/pause"                 31 seconds ago           Exited (0) 30 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1495
aee63f3263d9        k8s.gcr.io/pause:3.1   "/pause"                 32 seconds ago           Exited (0) 32 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1494
65a1ee0840d3        k8s.gcr.io/pause:3.1   "/pause"                 32 seconds ago           Exited (0) 32 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1487
e447512fb15f        k8s.gcr.io/pause:3.1   "/pause"                 33 seconds ago           Exited (0) 33 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1493
64292796e7b9        k8s.gcr.io/pause:3.1   "/pause"                 34 seconds ago           Exited (0) 33 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1492
04d356fa1c6d        k8s.gcr.io/pause:3.1   "/pause"                 35 seconds ago           Exited (0) 34 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1486
b18d3d152075        k8s.gcr.io/pause:3.1   "/pause"                 36 seconds ago           Exited (0) 35 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1491
12a791b9ac7b        k8s.gcr.io/pause:3.1   "/pause"                 37 seconds ago           Exited (0) 36 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1490
15f6b7cc3b5d        k8s.gcr.io/pause:3.1   "/pause"                 37 seconds ago           Exited (0) 36 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1485
e4ee063afd29        k8s.gcr.io/pause:3.1   "/pause"                 38 seconds ago           Exited (0) 37 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1489
7fe83f18f95e        k8s.gcr.io/pause:3.1   "/pause"                 38 seconds ago           Exited (0) 37 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1484
afba15ff242a        k8s.gcr.io/pause:3.1   "/pause"                 39 seconds ago           Exited (0) 38 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1488
d20927867473        k8s.gcr.io/pause:3.1   "/pause"                 40 seconds ago           Exited (0) 39 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1487
8ad5794df76d        k8s.gcr.io/pause:3.1   "/pause"                 40 seconds ago           Exited (0) 39 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1483
4e8ea53690c3        k8s.gcr.io/pause:3.1   "/pause"                 41 seconds ago           Exited (0) 40 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1486
c81c3465736e        k8s.gcr.io/pause:3.1   "/pause"                 42 seconds ago           Exited (0) 41 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1485
38d3b22275f5        k8s.gcr.io/pause:3.1   "/pause"                 43 seconds ago           Exited (0) 42 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1482
9f62fc818e94        k8s.gcr.io/pause:3.1   "/pause"                 44 seconds ago           Exited (0) 43 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1484
a1ba719ea71b        k8s.gcr.io/pause:3.1   "/pause"                 45 seconds ago           Exited (0) 44 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1481
1d9e60422c2e        k8s.gcr.io/pause:3.1   "/pause"                 46 seconds ago           Exited (0) 45 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1483
bf9c1461cbb3        k8s.gcr.io/pause:3.1   "/pause"                 47 seconds ago           Exited (0) 46 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1480
8bdc53364dea        k8s.gcr.io/pause:3.1   "/pause"                 48 seconds ago           Exited (0) 47 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1482
5f1fefb15e91        k8s.gcr.io/pause:3.1   "/pause"                 49 seconds ago           Exited (0) 48 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1479
6f787d13c236        k8s.gcr.io/pause:3.1   "/pause"                 50 seconds ago           Exited (0) 49 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1481
c083d6b66ace        k8s.gcr.io/pause:3.1   "/pause"                 51 seconds ago           Exited (0) 50 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1478
5847f2d5cfca        k8s.gcr.io/pause:3.1   "/pause"                 52 seconds ago           Exited (0) 51 seconds ago                               k8s_POD_coredns-78fcdf6894-gxzvk_kube-system_60f23ec4-a396-11e8-aaf5-88882f0da0b5_1477
4ce826d4506e        k8s.gcr.io/pause:3.1   "/pause"                 52 seconds ago           Exited (0) 51 seconds ago                               k8s_POD_coredns-78fcdf6894-qt2zq_kube-system_60f2d08e-a396-11e8-aaf5-88882f0da0b5_1480
f4410baaf5c3        f0fad859c909           "cp -f /etc/kube-f..."   26 minutes ago           Exited (0) 26 minutes ago                               k8s_install-cni_kube-flannel-ds-amd64-7xphb_kube-system_b9181d5d-a396-11e8-aaf5-88882f0da0b5_0
1da7df55b781        f0fad859c909           "/opt/bin/flanneld..."   32 minutes ago           Up 32 minutes                                           k8s_kube-flannel_kube-flannel-ds-amd64-7xphb_kube-system_b9181d5d-a396-11e8-aaf5-88882f0da0b5_0
```

**Comment by sebt3** [comment] 2018-12-24 13:32
Confirmed, this issue is because the kernel module "vxlan" is missing. Compile and load it to have flannel working

**Comment by rajatchopra** [comment] 2019-01-03 21:08
Closing this issue as per this [comment](https://github.com/coreos/flannel/issues/1028#issuecomment-449734834). 'vxlan' kernel module is a must for flannel overlay to work. Please re-open the issue if unresolved still.

**Closed by rajatchopra** 2019-01-03 21:08 UTC
