### ISSUE TITLE
cannot connect to internet from k8 pods. using flanneld configuration mentioned in coreos site

### ISSUE THREAD

**Issue by vinayk06** [coreos/flannel#539] opened 2016-10-31 16:40 UTC
Cannot connect to internet from k8 pods.
```
starting flanneld:
$systemctl start flanneld

-----------------------

$core@ip-192-168-212-22 ~ $ systemctl cat flanneld
# /usr/lib64/systemd/system/flanneld.service
[Unit]
Description=Network fabric for containers
Documentation=https://github.com/coreos/flannel
Requires=early-docker.service
After=etcd.service etcd2.service early-docker.service
Before=early-docker.target

[Service]
Type=notify
Restart=always
RestartSec=5
Environment="TMPDIR=/var/tmp/"
Environment="DOCKER_HOST=unix:///var/run/early-docker.sock"
Environment="FLANNEL_VER=0.5.5"
Environment="FLANNEL_IMG=quay.io/coreos/flannel"
Environment="ETCD_SSL_DIR=/etc/ssl/etcd"
Environment="FLANNEL_ENV_FILE=/run/flannel/options.env"
LimitNOFILE=40000
LimitNPROC=1048576
ExecStartPre=/sbin/modprobe ip_tables
ExecStartPre=/usr/bin/mkdir -p /run/flannel
ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR}
ExecStartPre=-/usr/bin/touch ${FLANNEL_ENV_FILE}

ExecStart=/usr/libexec/sdnotify-proxy /run/flannel/sd.sock \
  /usr/bin/docker run --net=host --privileged=true --rm \
  --volume=/run/flannel:/run/flannel \
  --env=NOTIFY_SOCKET=/run/flannel/sd.sock \
  --env=AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID} \
  --env=AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY} \
  --env-file=${FLANNEL_ENV_FILE} \
  --volume=/usr/share/ca-certificates:/etc/ssl/certs:ro \
  --volume=${ETCD_SSL_DIR}:${ETCD_SSL_DIR}:ro \
  ${FLANNEL_IMG}:${FLANNEL_VER} /opt/bin/flanneld --ip-masq=true

# Update docker options
ExecStartPost=/usr/bin/docker run --net=host --rm --volume=/run:/run \
  ${FLANNEL_IMG}:${FLANNEL_VER} \
  /opt/bin/mk-docker-opts.sh -d /run/flannel_docker_opts.env -i

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/flanneld.service.d/40-ExecStartPre-symlink.conf
[Service]
ExecStartPre=

-------------------

$ ip route show to match 224.0.0.13
default via 192.168.212.1 dev eth0  proto dhcp  src 192.168.212.22  metric 1024


cat /run/flannel/subnet.env
FLANNEL_NETWORK=10.2.0.0/16
FLANNEL_SUBNET=10.2.80.1/24
FLANNEL_MTU=8951
FLANNEL_IPMASQ=true

$ ifconfig
docker0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 10.2.80.1  netmask 255.255.255.0  broadcast 0.0.0.0
        ether 02:42:32:8a:87:7b  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 9001
        inet 192.168.212.22  netmask 255.255.255.192  broadcast 192.168.212.63
        inet6 fe80::10c4:ddff:fe27:fd0e  prefixlen 64  scopeid 0x20<link>
        ether 12:c4:dd:27:fd:0e  txqueuelen 1000  (Ethernet)
        RX packets 213463  bytes 280329092 (267.3 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 59167  bytes 13897569 (13.2 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

flannel.1: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 8951
        inet 10.2.80.0  netmask 255.255.0.0  broadcast 0.0.0.0
        inet6 fe80::e0e0:80ff:fe09:e466  prefixlen 64  scopeid 0x20<link>
        ether e2:e0:80:09:e4:66  txqueuelen 0  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 8 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1  (Local Loopback)
        RX packets 195154  bytes 127563089 (121.6 MiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 195154  bytes 127563089 (121.6 MiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

```

I see FLANNEL_IFACE=is not working or something can some one be the rescuer?

**Comment by tomdee** [comment] 2017-11-03 17:39
Hi @vinayk06, I can't work out what the problem is and this has been open for a long time so closing. If you're still having problems then get back in touch.

**Closed by tomdee** 2017-11-03 17:39 UTC
Labels: component/masq, kind/support
