### ISSUE TITLE
Question: How to setup a mini cluster with flannel on ec2

### ISSUE THREAD

**Issue by misakwa** [coreos/flannel#218] opened 2015-06-22 15:08 UTC
I have been experiencing some issues setting up a small cluster on ec2 from following the docs.

Specs:
OS: CoreOS stable (681.2.0) - ami-5f2f5528
Etcd: etcd version 2.0.10
Fleet: fleetd version 0.10.2
Flannel: 0.4.0
Instance type: t2.micro

Here is my cloud init config:

```
#cloud-config

---
coreos:
  etcd2:
    advertise-client-urls: http://$private_ipv4:2379
    initial-advertise-peer-urls: http://$private_ipv4:2380
    listen-client-urls: http://0.0.0.0:2379,http://0.0.0.0:4001
    listen-peer-urls: http://$private_ipv4:2380,http://0.0.0.0:7001
    discovery: https://discovery.etcd.io/<my-token>
  fleet:
    public-ip: $private_ipv4
    metadata: role=services,disk=ssd,region=us-east,provider=amazon
  units:
    - name: etcd2.service
      command: start
    - name: fleet.service
      command: start
    - name: flanneld.service
      drop-ins:
      - name: 50-network-config.conf
        content: |
          [Service]
          ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config '{ "Network": "10.1.0.0/16" }'
      command: start
    - name: docker-tcp.socket
      command: start
      enable: true
      content: |
        [Unit]
        Description=Docker Socket for the API

        [Socket]
        ListenStream=2375
        Service=docker.service
        BindIPv6Only=both

        [Install]
        WantedBy=sockets.target
```

I spun up 9 instances (using an auto scaling group) all running with the same cloud init config (from a launch config/template).
journalctl shows:

```
Jun 22 13:10:57 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: Pulling repository quay.io/coreos/flannel
Jun 22 13:10:57 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 73b8daf50cec: Pulling image (0.4.0) from quay.io/coreos/flannel
Jun 22 13:10:57 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 73b8daf50cec: Pulling image (0.4.0) from quay.io/coreos/flannel, endpoint: https://quay.io/v1/
Jun 22 13:10:57 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 73b8daf50cec: Pulling dependent layers
Jun 22 13:10:57 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 91a6195f52a2: Pulling metadata
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 91a6195f52a2: Pulling fs layer
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 91a6195f52a2: Error pulling dependent layers
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 73b8daf50cec: Error pulling image (0.4.0) from quay.io/coreos/flannel, endpoint: https://quay.io/v1/, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: 73b8daf50cec: Error pulling image (0.4.0) from quay.io/coreos/flannel, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal dockerd[596]: Error pulling image (0.4.0) from quay.io/coreos/flannel, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal dockerd[596]: time="2015-06-22T13:10:58Z" level=info msg="-job pull(quay.io/coreos/flannel, 0.4.0) = ERR (1)"
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal sdnotify-proxy[4388]: time="2015-06-22T13:10:58Z" level=fatal msg="Error pulling image (0.4.0) from quay.io/coreos/flannel, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)"
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal systemd[1]: flanneld.service: main process exited, code=exited, status=1/FAILURE
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal systemd[1]: Failed to start Network fabric for containers.
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal systemd[1]: Unit flanneld.service entered failed state.
Jun 22 13:10:58 ip-172-31-36-121.ec2.internal systemd[1]: flanneld.service failed.
```

Any help will be much appreciated.

Thanks.

**Comment by jzelinskie** [comment] 2015-06-22 20:42
Is this happening across all of the machines or is this a transient issue?

**Comment by misakwa** [comment] 2015-06-22 20:48
Its happening across all the machines.

**Comment by misakwa** [comment] 2015-06-22 20:50
I also tried pulling the flannel image manually on one of the boxes and it showed the same error with pulling one of the layers.

**Comment by eyakubovich** [comment] 2015-06-22 21:04
@misakwa Are you pulling from quay.io with credentials set (logged in) or in an anonymous fashion?

**Comment by misakwa** [comment] 2015-06-22 21:04
I'm pulling anonymously.

**Comment by misakwa** [comment] 2015-06-22 21:05
I tried manually with credentials though but still no luck.

**Comment by eyakubovich** [comment] 2015-06-22 21:13
There's a `-D` option (debug) that could help us a little to troubleshoot this. With CoreOS set up, it uses a secondary version of docker (eary-docker) to pull down flannel. Can you put the following drop-in to add this option to the daemon:

```
/etc/systemd/system/flanneld.d/10-debug.conf

ExecStart=
ExecStart=/usr/lib/coreos/dockerd --daemon -D --host=fd:// --bridge=none --iptables=false --ip-masq=false --graph=/var/lib/early-docker --pidfile=/var/run/early-docker.pid
```

Then do `sudo systemctl daemon-reload` and `sudo systemctl start flanneld` to try again.

**Comment by eyakubovich** [comment] 2015-06-22 21:16
@misakwa I just updated the comment above to add missing `[Service]` line.

**Comment by misakwa** [comment] 2015-06-23 00:41
@eyakubovich, I added the debug drop-in you suggested and this is what I got back from journalctl

```
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal systemd[1]: Starting Network fabric for containers...
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal etcdctl[2010]: { "Network": "10.1.0.0/16" }
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="waiting for daemon to initialize"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=info msg="+job serveapi(fd://)"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=info msg="Listening for HTTP on fd ()"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /commit"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /images/load"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/create"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /exec/{name:.*}/start"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /exec/{name:.*}/resize"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/restart"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/wait"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/resize"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/attach"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/copy"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /auth"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /images/create"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /images/{name:.*}/push"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /images/{name:.*}/tag"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/kill"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /build"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/pause"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/start"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/stop"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/exec"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering POST, /containers/{name:.*}/rename"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering DELETE, /containers/{name:.*}"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering DELETE, /images/{name:.*}"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering OPTIONS, "
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering GET, /images/get"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=debug msg="Registering GET, /containers/{name:.*}/export"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal dockerd[2017]: time="2015-06-23T00:39:16Z" level=fatal msg="Shutting down daemon due to errors: pid file found, ensure docker is not running or delete /var/run/early-docker.pid"
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal systemd[1]: flanneld.service: main process exited, code=exited, status=1/FAILURE
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal systemd[1]: Failed to start Network fabric for containers.
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal systemd[1]: Unit flanneld.service entered failed state.
Jun 23 00:39:16 ip-172-31-36-218.ec2.internal systemd[1]: flanneld.service failed.
```

**Comment by eyakubovich** [comment] 2015-06-23 00:52
@misakwa I think the problem is that early-docker was still running or the `/var/run/early-docker.pid` file didn't get cleaned up. Can you reboot the node to make sure it starts clean.

**Comment by misakwa** [comment] 2015-06-23 00:53
I manually removed the pid file and then started getting this:
```
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal systemd[1]: flanneld.service holdoff time over, scheduling restart.
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal systemd[1]: Starting Network fabric for containers...
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal etcdctl[4984]: { "Network": "10.1.0.0/16" }
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="waiting for daemon to initialize"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="+job serveapi(fd://)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="Listening for HTTP on fd ()"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /info"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/{name:.*}/history"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/{name:.*}/json"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/changes"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/{name:.*}/get"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/export"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/attach/ws"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /events"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /version"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/json"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/get"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/json"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/top"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/logs"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /_ping"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/viz"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /images/search"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/ps"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/json"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /containers/{name:.*}/stats"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering GET, /exec/{id:.*}/json"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /images/create"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/pause"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/restart"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/resize"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/copy"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/exec"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /auth"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /build"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/rename"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /images/{name:.*}/push"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /images/{name:.*}/tag"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/stop"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/wait"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/attach"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /exec/{name:.*}/start"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /commit"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /images/load"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /exec/{name:.*}/resize"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/unpause"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/start"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/create"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering POST, /containers/{name:.*}/kill"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering DELETE, /containers/{name:.*}"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering DELETE, /images/{name:.*}"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Registering OPTIONS, "
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Using graph driver overlay"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Creating images graph"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Restored 0 elements"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Creating repository list"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: No sockets found
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="-job serveapi(fd://) = ERR (1)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=error msg="ServeAPI error: No sockets found"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal systemd[1]: Scope libcontainer-4991-systemd-test-default-dependencies.scope has no PIDs. Refusing.
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="Restarting containers..."
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="docker daemon: 1.6.2 7c8fca2-dirty; execdriver: native-0.2; graphdriver: overlay"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="+job acceptconnections()"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="-job acceptconnections() = OK (0)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=info msg="Daemon has completed initialization"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=debug msg="starting clean shutdown of all containers..."
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[4991]: time="2015-06-23T00:49:09Z" level=fatal msg="Shutting down due to ServeAPI error: No sockets found"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal systemd[1]: flanneld.service: main process exited, code=exited, status=1/FAILURE
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="POST /v1.18/containers/create"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="+job create()"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: No such image: quay.io/coreos/flannel:0.4.0 (tag: 0.4.0)
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="-job create() = ERR (1)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=error msg="Handler for POST /containers/create returned error: No such image: quay.io/coreos/flannel:0.4.0 (tag: 0.4.0)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=error msg="HTTP Error: statusCode=404 No such image: quay.io/coreos/flannel:0.4.0 (tag: 0.4.0)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal docker[5000]: Unable to find image 'quay.io/coreos/flannel:0.4.0' locally
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="POST /v1.18/images/create?fromImage=quay.io%2Fcoreos%2Fflannel&tag=0.4.0"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="+job pull(quay.io/coreos/flannel, 0.4.0)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="+job resolve_repository(quay.io/coreos/flannel)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal dockerd[589]: time="2015-06-23T00:49:09Z" level=info msg="-job resolve_repository(quay.io/coreos/flannel) = OK (0)"
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal docker[5000]: Pulling repository quay.io/coreos/flannel
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal docker[5000]: 73b8daf50cec: Pulling image (0.4.0) from quay.io/coreos/flannel
Jun 23 00:49:09 ip-172-31-36-218.ec2.internal docker[5000]: 73b8daf50cec: Pulling image (0.4.0) from quay.io/coreos/flannel, endpoint: https://quay.io/v1/
Jun 23 00:49:10 ip-172-31-36-218.ec2.internal docker[5000]: 73b8daf50cec: Pulling dependent layers
Jun 23 00:49:10 ip-172-31-36-218.ec2.internal docker[5000]: 91a6195f52a2: Pulling metadata
Jun 23 00:49:10 ip-172-31-36-218.ec2.internal docker[5000]: 91a6195f52a2: Pulling fs layer
Jun 23 00:49:11 ip-172-31-36-218.ec2.internal docker[5000]: 91a6195f52a2: Error pulling dependent layers
Jun 23 00:49:11 ip-172-31-36-218.ec2.internal docker[5000]: 73b8daf50cec: Error pulling image (0.4.0) from quay.io/coreos/flannel, endpoint: https://quay.io/v1/, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
Jun 23 00:49:11 ip-172-31-36-218.ec2.internal docker[5000]: 73b8daf50cec: Error pulling image (0.4.0) from quay.io/coreos/flannel, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
Jun 23 00:49:11 ip-172-31-36-218.ec2.internal dockerd[589]: Error pulling image (0.4.0) from quay.io/coreos/flannel, Server error: Status 403 while fetching image layer (91a6195f52a2c01646c3c5952c1fcc8e15f9d2a5ac049edb0ec8412a1cd1c6fe)
J
```

**Comment by misakwa** [comment] 2015-06-23 01:00
I get the same errors after reboot.
I don't know if this is important but I recreated my cluster from scratch so all the instances are completely new.
I may also have missed this information from the start but I am running my cluster in a vpc with 4-subnets which can all talk to each other - I'm using a security group that allows that.

**Comment by josephschorr** [comment] 2015-06-23 01:00
@misakwa Does your VPC allow access to Amazon S3 machines outside of the cluster?

**Comment by misakwa** [comment] 2015-06-23 01:03
I did create a vpc endpoint with an s3 bucket policy to run a private registry but I'm not using that at the moment. Also I am able to get the cluster running with flannel disabled.

**Comment by josephschorr** [comment] 2015-06-23 01:05
@misakwa To clarify: Can the machines trying to pull that image access the public S3 endpoints? When you do a pull from `quay.io`, we 302 redirect to S3, and if your VPC cannot access those URLs, the pull will fail.

**Comment by eyakubovich** [comment] 2015-06-23 01:18
@misakwa can you `curl https://s3.amazonaws.com/quay-registry/okay.txt` from the bad node and see if at least that works. It should return `quay-okay` string.

**Comment by misakwa** [comment] 2015-06-23 01:34
@josephschorr: The initial s3 policy I created for my vpc endpoint was restricting access but it works after relaxing the policy (completely removing the endpoint)
@eyakubovich: I was able to get `quay-okay` from curling the s3 key provided above. 
However flanneld is still unable to start.

**Comment by misakwa** [comment] 2015-06-23 01:38
I got this back from `systemctl status flanneld.service`:

```
● flanneld.service - Network fabric for containers
   Loaded: loaded (/usr/lib64/systemd/system/flanneld.service; static; vendor preset: disabled)
  Drop-In: /etc/systemd/system/flanneld.service.d
           └─10-debug.conf, 50-network-config.conf
   Active: activating (auto-restart) (Result: exit-code) since Tue 2015-06-23 01:36:18 ; 858ms ago
     Docs: https://github.com/coreos/flannel
  Process: 2460 ExecStart=/usr/lib/coreos/dockerd --daemon -D --host=fd:// --bridge=none --iptables=false --ip-masq=false --graph=/var/lib/early-docker --pidfile=/var/run/early-docker.pid (code=exited, status=1/FAILURE)
  Process: 2452 ExecStartPre=/usr/bin/etcdctl set /coreos.com/network/config { "Network": "10.1.0.0/16" } (code=exited, status=0/SUCCESS)
  Process: 2450 ExecStartPre=/usr/bin/touch /run/flannel/options.env (code=exited, status=0/SUCCESS)
  Process: 2448 ExecStartPre=/usr/bin/mkdir -p ${ETCD_SSL_DIR} (code=exited, status=0/SUCCESS)
  Process: 2446 ExecStartPre=/usr/bin/mkdir -p /run/flannel (code=exited, status=0/SUCCESS)
  Process: 2443 ExecStartPre=/sbin/modprobe ip_tables (code=exited, status=0/SUCCESS)
 Main PID: 2460 (code=exited, status=1/FAILURE)

Jun 23 01:36:18 ip-172-31-1-222.ec2.internal systemd[1]: flanneld.service: main process exited, code=exited, status=1/FAILURE
Jun 23 01:36:18 ip-172-31-1-222.ec2.internal systemd[1]: Failed to start Network fabric for containers.
Jun 23 01:36:18 ip-172-31-1-222.ec2.internal systemd[1]: Unit flanneld.service entered failed state.
Jun 23 01:36:18 ip-172-31-1-222.ec2.internal systemd[1]: flanneld.service failed.
```

**Comment by misakwa** [comment] 2015-06-23 01:50
And btw, I was able to pull the flannel image manually on the node.

**Comment by eyakubovich** [comment] 2015-06-23 02:13
@misakwa well, that's still progress. Can you paste the output of `journalctl -u flanneld` again?

**Comment by misakwa** [comment] 2015-06-23 02:50
Weirdly I got the cluster working after destroying and rebuilding with the original cloud config. The only difference is that the vpc endpoint no longer exists and it took a couple of recreations to get it working.
It looks like the problem is with having a vpc endpoint that does not allow pulling the flannel image. I'm not sure why it persisted a couple of times after I removed the vpc endpoint but everything seems to be working now.

**Comment by misakwa** [comment] 2015-06-23 02:54
I really appreciate the prompt and consistent response from you all. Great work on the tools btw and thanks again.

**Comment by misakwa** [comment] 2015-06-23 03:05
Let me know when I can close this issue or if there is any more information I can provide that will be useful to others trying to setup a cluster with flannel on ec2.

**Comment by eyakubovich** [comment] 2015-06-23 05:08
@misakwa Glad to hear it's working. I think you can close this issue.

**Closed** 2015-06-23 11:18 UTC
