### ISSUE TITLE
VXLAN mode is broken for kernel 3.19.0

### ISSUE THREAD

**Issue by klizhentas** [coreos/flannel#267] opened 2015-07-29 00:06 UTC
I've installed flanneld and docker on Ubuntu 14.04 with upgraded kernel 3.19
The ARP entry of the remote flannel.1 was not added to the ARP table.

After downgrading kernel back to 3.13, the issue was resolved - and ARP entry was added. I'm happy to help fixing the issue, if you point me to the right direction.

Let me know if you have any questions.

**Comment by klizhentas** [comment] 2015-07-29 17:58
just tried 3.18.18-031818-generic with the same result. Seems something have changed since 3.13

**Comment by eyakubovich** [comment] 2015-07-30 00:20
Also reported in https://github.com/coreos/flannel/issues/260

We need to figure out which version fixed it again. Would actually be great to understand what the actual bug was.

**Comment by klizhentas** [comment] 2015-07-30 01:08
@eyakubovich do you know the version > 3.13 that works?

**Comment by eyakubovich** [comment] 2015-07-30 01:12
@klizhentas I don't. I'll try to try a few versions to see which ones work but it may not be till next week. Do you have time to try other ones?

**Comment by klizhentas** [comment] 2015-07-30 01:15
sure, is there any particular version you would like to check?

**Comment by klizhentas** [comment] 2015-07-30 01:16
also, can you point me to the chunk of code that you think is not triggered? I can add debugging info and see what's not working

**Comment by eyakubovich** [comment] 2015-07-30 01:24
I'd be interested in 3.18 and something from 4.x series.

I think the ARP misses might not be getting through: https://github.com/coreos/flannel/blob/master/backend/vxlan/device.go#L208

That's my only guess for now.

**Comment by klizhentas** [comment] 2015-07-30 01:25
I've tried latest stable `3.18.18-031818-generic` and it has the same problem, I will try 4.x and will update the ticket

**Comment by changx** [comment] 2015-07-30 04:24
I have the same issue on 3.19.3-031903-generic,  it works on 3.16.0-0.bpo ( aka 3.16.7-ckt11   wheezy-backports ) , but I can not reverse back due to 3.16.7 racing condition under kvm :/ .

**Comment by eyakubovich** [comment] 2015-08-03 22:56
I can reproduce this on my Ubuntu box (3.19.0-23). You can see that ARP (L3) misses are not delivered to flannel. Yet when I booted CoreOS 640.0.0 (3.19.3), it works fine. Could it be that the problem is with one of the Ubuntu patches?

**Comment by eyakubovich** [comment] 2015-08-04 19:48
Fixed in #272

**Closed by eyakubovich** 2015-08-04 19:48 UTC

**Comment by klizhentas** [comment] 2015-08-06 19:47
tested on the 3.19 and it now works fine, thanks!
