### ISSUE TITLE
"Watch subnets: client: etcd cluster is unavailable or misconfigured" messages but network works fine

### ISSUE THREAD

**Issue by TaiSHiNet** [coreos/flannel#508] opened 2016-09-16 19:23 UTC
Hi!

Flannel keeps repeating these messages:

```
Sep 16 18:33:29 ip-10-0-3-249.ec2.internal rkt[1056]: E0916 18:33:29.054097 01056 watch.go:41] Watch subnets: client: etcd cluster is unavailable or misconfigured
```

Although overlay network is working fine (I have a kubernetes cluster set up) and etcd is accessible from the nodes.
Flanneld on the master/etcd output no errors.
Setup:
1x etcd/kube-master
3x kube-minions

It doesn't seem to affect anything but still wanted to bring attention to you.
Bests

**Comment by tomdee** [comment] 2016-09-19 16:15
How are you starting flannel? I suspect that you're not passing in the location of your etcd server(s), which is why it's working on your master but no other nodes.

**Comment by TaiSHiNet** [comment] 2016-09-19 19:06
I was starting flannel with cloud-config, network setup and lease were acquired (I had container-to-container connectivity), yet that message kept popping up. 
As I said, didn't have any negative effect on the networking functions but it was worrisome to see on the journal.

**Comment by tomdee** [comment] 2017-04-28 01:15
Assuming this is caused by AWS ELB timeouts. So closing and tracking elsewhere.

**Closed by tomdee** 2017-04-28 01:15 UTC
Labels: kind/support
