### ISSUE TITLE
Env file gets overridden by the systemd service

### ISSUE THREAD

**Issue by aabed** [coreos/flannel#429] opened 2016-04-21 19:24 UTC
/run/flanneld/options.env
works fine for the first time, but when I reboot it's all gone

**Comment by tomdee** [comment] 2016-06-08 00:43
@aabed Can you describe your environment a little more? This is the systemd service file included in CoreOS right? Which version of Coreos did you see this problem on?

**Comment by eyakubovich** [comment] 2016-07-16 18:29
`/run` is usually tmpfs so will be gone on a reboot. If you want settings to persist, you will need to use `/etc`.

**Comment by tomdee** [comment] 2017-04-27 23:02
Closing as I'm not sure what the issue is. @aabed Please reopen if you're still having a problem here.

**Closed by tomdee** 2017-04-27 23:02 UTC
Labels: kind/bug, reviewed/needs more information
