### ISSUE TITLE
Can't access remote host flannel network when using port 8472

### ISSUE THREAD

**Issue by xcompass** [coreos/flannel#423] opened 2016-03-28 10:10 UTC
I was troubleshooting why I can't access remote nodes on flannel network. I found it has something to do port 8472. Here is what my environment is and what I did:

**Environment**:
* 2 worker coreos 991 nodes on vcloud (VMWare) on the same subnet: 10.93.0.129 (Host A) and 10.93.0.131(Host B). So no firewall in between
* Flannel network: Host A 10.2.7.0 and Host B 10.2.72.0
* Flannel network config: ```etcdctl set /coreos.com/network/config '{ "Network": "10.2.0.0/16", "Backend": {"Type": "vxlan"}}'```

**What I did**:
* ping 10.2.72.0 from host a, nothing
* run tcpdump on both hosts: ```tcpdump -i ens192 -v "port 8472"``` and ping from host A. Only host A has package sending out. No reply and nothing on host B. 
* reversed (ping from host B), the same.
* tcpdump on flannel.1 interface. similar result
* used ```nc -u 10.93.0.131 (host B) 8472``` from host A, Same tcpdump result: packages went out from host A but did not reach to host B
* I also tried the same setup on Virtualbox, it works fine.

There is no firewall rule setup on both hosts in iptables. I can't think of anything else that blocking the traffic. So I decided to switch to udp backend and it works. Then I tried to change to port of vxlan backend to 8473. It also works...
```
etcdctl set /coreos.com/network/config '{ "Network": "10.2.0.0/16", "Backend": {"Type":
 "vxlan", "Port": 8473}}'
```

It makes me wonder if kernel is blocking 8472 for some reason?

Also, I noticed that the port opened on hosts are not 8473, but 6433
```
compass@f2 ~ $ netstat -anu
Active Internet connections (servers and established)
Proto Recv-Q Send-Q Local Address           Foreign Address         State
udp        0      0 10.93.0.131:68          0.0.0.0:*
udp        0      0 0.0.0.0:5355            0.0.0.0:*
udp        0      0 0.0.0.0:6433            0.0.0.0:*
udp6       0      0 :::546                  :::*
udp6       0      0 :::5355                 :::*
```
Is it a bug?

**Comment by hustcat** [comment] 2016-03-31 13:47
PR #421 to fix this bug

**Comment by tomdee** [comment] 2016-06-14 17:29
Bug in netlink which has been fixed https://github.com/vishvananda/netlink/pull/111

**Comment by xcompass** [comment] 2016-06-14 23:07
Great. Looking forward for that to be merged.

**Comment by jonlangemak** [comment] 2016-07-08 13:23
Any update on this one?  Im running into a bug where even when I specify a VXLAN port for flannel and it ends up being off each time.  Im thinking this could be related.

**Comment by tomdee** [comment] 2016-07-08 17:20
It's now fixed in master. I'm planning to do a release with the fix in the next few weeks.

**Comment by steveeJ** [comment] 2016-07-12 01:14
Since the issue is fixed in the repo the issue can be closed now, thanks @tomdee!

**Closed** 2016-07-12 01:15 UTC
Labels: dependency/external
