### ISSUE TITLE
Flannel eats all memory and cpu.

### ISSUE THREAD

**Issue by ssergiienko** [coreos/flannel#337] opened 2015-10-06 11:30 UTC
flannel-0.5.1

On Master:

```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                  
13842 etcd      20   0   42232  24792   2916 S  93.4  0.9 607:33.77 etcd                                                                                                                     
   41 root      20   0       0      0      0 S   4.3  0.0  18:35.42 rcu_sched                                                                                                                
  418 root      20   0   51208  10708  10544 S   3.7  0.4  33:58.41 systemd-journal                                                                                                          
14116 root      20   0 2428468 1.992g   2096 S   3.3 73.4  51:59.73 flanneld 
```

```
[root@static ~]# systemctl status flanneld -l
flanneld.service - Flanneld overlay address etcd agent
   Loaded: loaded (/etc/systemd/system/flanneld.service; enabled)
   Active: active (running) since Fri 2015-09-25 13:30:58 EEST; 1 day 2h ago
 Main PID: 14116 (flanneld)
   CGroup: /system.slice/flanneld.service
           └─14116 /usr/bin/flanneld -etcd-endpoints=http://127.0.0.1:4001 -etcd-prefix=/some/network/ --iface=enp0s5

933703 14116 hostgw.go:136] Subnet added: 10.254.53.0/24 via IP.IP.IP.IP
933827 14116 hostgw.go:152] Error adding route to 10.254.53.0/24 via IP.IP.IP.IP: file exists
26 16:03:32 DEBUG: rawWatch /some/network/subnets []
26 16:03:32 DEBUG: get /some/network/subnets [http://127.0.0.1:4001]
26 16:03:32 DEBUG: Connecting to etcd: attempt 1 for keys/some/network/subnets?recursive=true&wait=true&waitIndex=654925
26 16:03:32 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/some/network/subnets?recursive=true&wait=true&waitIndex=654925 | method GET
26 16:03:32 DEBUG: recv.response.from
26 16:03:32 DEBUG: recv.response.from
26 16:03:32 DEBUG: recv.success
26 16:03:32 DEBUG: recv.success
26 16:03:32 DEBUG: rawWatch /some/network/subnets []
26 16:03:32 DEBUG: get /some/network/subnets [http://127.0.0.1:4001]
26 16:03:32 DEBUG: Connecting to etcd: attempt 1 for keys/some/network/subnets?recursive=true&wait=true&waitIndex=654925
26 16:03:32 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/some/network/subnets?recursive=true&wait=true&waitIndex=654925 | method GET
971470 14116 hostgw.go:136] Subnet added: 10.254.9.0/24 via IP.IP.IP.IP
971578 14116 hostgw.go:152] Error adding route to 10.254.9.0/24 via IP.IP.IP.IP: file exists
26 16:03:32 DEBUG: rawWatch /some/network/subnets []
26 16:03:32 DEBUG: get /some/network/subnets [http://127.0.0.1:4001]
26 16:03:32 DEBUG: Connecting to etcd: attempt 1 for keys/some/network/subnets?recursive=true&wait=true&waitIndex=654926
26 16:03:32 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/some/network/subnets?recursive=true&wait=true&waitIndex=654926 | method GET
26 16:03:32 DEBUG: recv.response.from
26 16:03:32 DEBUG: recv.success
26 16:03:32 DEBUG: rawWatch /some/network/subnets []
26 16:03:32 DEBUG: get /some/network/subnets [http://127.0.0.1:4001]
26 16:03:32 DEBUG: Connecting to etcd: attempt 1 for keys/some/network/subnets?recursive=true&wait=true&waitIndex=654926
26 16:03:32 DEBUG: send.request.to http://127.0.0.1:4001/v2/keys/some/network/subnets?recursive=true&wait=true&waitIndex=654926 | method GET
982793 14116 hostgw.go:136] Subnet added: 10.254.53.0/24 via IP.IP.IP.IP
982919 14116 hostgw.go:152] Error adding route to 10.254.53.0/24 via IP.IP.IP.IP: file exists
```

On nodes same thing with same errors
```
  PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                                                                                  
 5977 root      20   0  757720 496720   4704 S  62.1 26.4  78:16.53 flanneld                                                                                                                 
 9211 root      20   0 1212332  53584   7400 S   5.3  2.8 129:31.62 kubelet                                                                                                                  
  420 root      20   0   56184   4208   4068 S   4.0  0.2  43:32.66 systemd-journal
```
Restarting flanneld doesn't helps. Even reboot doesn't helps.

**Comment by jonboulle** [comment] 2015-10-06 19:50
Any chance you can reproduce this on a more recent version of flannel? (preferably v0.5.3). There have been some significant changes since v0.5.1 like moving to a new etcd client.

**Comment by ssergiienko** [comment] 2015-10-07 06:56
We already started to build new package(v0.5.3) and soon i'll write results. This bug is not always reproducible, i have seen it in older versions too but this time even restart of flanneld, etcd, or even VM is not helps.

**Comment by ssergiienko** [comment] 2015-10-07 13:20
Solved. With 0.5.3 flannel bug is the same as with other versions, but more meaningful logs helped to see where problem was.

On master (on which etcd is running) was failed ntpd and system time was in past (one week). So flanneld recieved new ttl that already expired and, as far as i understand, it tries to reconnect continuously without any wait or "max retry count" and thus eats all cpu and memory.

```
flanneld[27346]: I1007 11:34:53.837620 27346 renew.go:41] Lease renewed, new expiration: 2015-09-28 10:41:08.292993055 +0000 UTC
```

After restarting ntpd on master and restarting flanneld all works fine again. I think flannel should somehow handle such cases and print warnings or even errors. Maybe pause pulling for a certain time or stop after max count.

**Comment by eyakubovich** [comment] 2015-10-08 18:45
Thank you for tracking this down. You're right, it should slow down to 1 sec retry and issue warnings. Opened https://github.com/coreos/flannel/issues/340 to track.

**Closed by eyakubovich** 2015-10-08 18:45 UTC
Labels: area/performance, kind/bug
